language: python
os:
  - linux
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ./run_test.sh # or py.test for Python versions 3.5 and below
